exp_name: 'DIRL+CCR'
gpu_id: [0]
logger:
    display_id: 9908
model:
    transformer_encoder:
        input_dim: 2048
        feat_dim: 1024
        emb_dim: 512
        att_dim: 512
        att_head: 8
        att_layer: 2
        dim: 128
    transformer_decoder:
        input_dim: 2048
        word_dim: 300
        att_dim: 512
        att_head: 8
        att_layer: 2
        vocab_size: 87
        seq_length: 40
        share_wd_cls_weight: False
        label_smoothing: 0.0

data:
    dataset: 'rcc_dataset_transformer_dc'
    vocab_json: './clevr_dc/transformer_vocab.json'
    h5_label_file: './clevr_dc/transformer_labels.h5'
    default_feature_dir: './clevr_dc/features'
    semantic_feature_dir: './clevr_dc/sc_features'
    default_img_dir: './clevr_dc/images'
    semantic_img_dir: './clevr_dc/sc_images'
    splits_json: './clevr_dc/splits.json'
    train:
        batch_size: 128
train:
    max_iter: 13000
    snapshot_interval: 1000
    grad_clip: -1.0
    optim:
        type: 'adam'
        lr: 0.0002
        weight_decay: 0.0
